# Generated by Django 4.0.3 on 2022-04-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_create_message_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
